# Generated by Django 5.2.6 on 2025-09-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('pnum', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='age',
        ),
    ]
